### PR TITLE
Change test file encoding.

### PR DESCRIPTION
**Pull request by cool8jay**
Change test file encoding.

### CODE REVIEW

**Comment by mr-fixit** [comment]
Maybe I'm missing something, but why change the encoding?  

Issue #65 is about parsing **that** file, not one with different encoding.

**Comment by jomnius** [comment]
Since I was involved with issue #65, I can comment: I had no control whatsoever over the file encoding, therefore this kind of fix of changing test file encoding would not be useful for me.

However that was several years ago and the project, where I had this encoding problem, doesn't exist any more.

**Comment by mr-fixit** [comment]
@davedelong I recommend denying this PR.

**Comment by davedelong** [comment]
If the file for issue #65 is causing other issues, we should fix those issues without breaking the test case for issue #65.

**Pull request closed without merging**
